# Generated by Django 3.0.7 on 2020-06-08 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('iin', models.IntegerField()),
                ('marriage', models.CharField(choices=[('single', 'single'), ('married', 'married')], max_length=20)),
                ('education', models.CharField(choices=[('associate', 'associate'), ('bachelor', 'bachelor'), ('master', 'master'), ('doctor', 'doctor')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=200)),
                ('workplace', models.CharField(max_length=200)),
                ('income', models.IntegerField()),
                ('additional_income', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('limit_bal', models.IntegerField()),
                ('pay_0', models.IntegerField()),
                ('pay_2', models.IntegerField()),
                ('pay_6', models.IntegerField()),
                ('bill_amt5', models.IntegerField()),
                ('pay_amt1', models.IntegerField()),
                ('pay_amt2', models.IntegerField()),
                ('pay_amt3', models.IntegerField()),
                ('pay_amt4', models.IntegerField()),
                ('pay_amt5', models.IntegerField()),
                ('pay_amt6', models.IntegerField()),
                ('proba', models.FloatField()),
                ('score', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.RequestDetails')),
            ],
        ),
    ]
